location = /ac {
    if ($scheme = http) { return 308 https://$host/ac/; }
    return 302 /ac/;
}
location ^~ /ac/ {
    if ($scheme = http) { return 308 https://$host$request_uri; }
    client_max_body_size 17m;
    proxy_pass http://127.0.0.1:8080/;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /ac/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_buffering off;
    proxy_read_timeout 90s;
}
